
set(IMGUI_APP_PLATFORM "SDL2" CACHE STRING "Platform Binding")
set(IMGUI_APP_PLATFORM_SDL2 OFF)

if(IMGUI_APP_PLATFORM STREQUAL "SDL2")
  set(IMGUI_APP_PLATFORM_SDL2 ON)
endif()

if(IMGUI_APP_PLATFORM_SDL2) # SDL2
  find_package(SDL2 REQUIRED)
  set(IMGUI_APP_PLATFORM_INCLIUDE_DIRS ${SDL2_INCLUDE_DIRS})
  set(IMGUI_APP_PLATFORM_LIBRARIES ${SDL2_LIBRARIES})
  set(IMGUI_APP_PLATFORM_SOURCES ${IMGUI_EXAMPLE_DIR}/imgui_impl_sdl.cpp)
endif()
