
# Renderer Bindings
set(IMGUI_APP_RENDERER "OpenGL3" CACHE STRING "Renderer Binding")
set(IMGUI_APP_RENDERER_OPENGL OFF)
set(IMGUI_APP_RENDERER_OPENGL2 OFF)
set(IMGUI_APP_RENDERER_OPENGL3 OFF)
set(IMGUI_APP_RENDERER_VULKAN OFF)

if(IMGUI_APP_RENDERER STREQUAL "OpenGL2")
  set(IMGUI_APP_RENDERER_OPENGL ON)
  set(IMGUI_APP_RENDERER_OPENGL2 ON)
elseif(IMGUI_APP_RENDERER STREQUAL "OpenGL3")
  set(IMGUI_APP_RENDERER_OPENGL ON)
  set(IMGUI_APP_RENDERER_OPENGL3 ON)
elseif(IMGUI_APP_RENDERER STREQUAL "Vulkan")
  set(IMGUI_APP_RENDERER_VULKAN ON)
endif()

if(IMGUI_APP_RENDERER_OPENGL) # OpenGL
  find_package(OpenGL REQUIRED)
  set(IMGUI_APP_RENDERER_LIBRARIES ${OPENGL_LIBRARIES})
  set(IMGUI_APP_RENDERER_INCLIUDE_DIRS ${OPENGL_INCLUDE_DIRS})

  if(IMGUI_APP_RENDERER_OPENGL2)
    set(IMGUI_APP_RENDERER_SOURCES ${IMGUI_EXAMPLE_DIR}/imgui_impl_opengl2.cpp)
  elseif(IMGUI_APP_RENDERER_OPENGL3)
    set(IMGUI_APP_RENDERER_SOURCES ${IMGUI_EXAMPLE_DIR}/imgui_impl_opengl3.cpp)
  endif()

elseif(IMGUI_APP_RENDERER_VULKAN) # Vulkan
  find_package(Vulkan REQUIRED)
  set(IMGUI_APP_RENDERER_LIBRARIES ${Vulkan_LIBRARIES})
  set(IMGUI_APP_RENDERER_INCLIUDE_DIRS ${Vulkan_INCLUDE_DIRS})
  set(IMGUI_APP_RENDERER_SOURCES ${IMGUI_EXAMPLE_DIR}/imgui_impl_vulkan.cpp)

  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(-DIMGUI_VULKAN_DEBUG_REPORT)
  endif()
endif()

# OpenGL Loaders
set(IMGUI_APP_OPENGL_LOADER "GLEW" CACHE STRING "OpenGL Loader")
set(IMGUI_APP_OPENGL_LOADER_GLEW OFF)
set(IMGUI_APP_OPENGL_LOADER_GLAD OFF)

if(NOT IMGUI_APP_RENDERER_OPENGL)
  # unnecessary
elseif(IMGUI_APP_OPENGL_LOADER STREQUAL "GLEW")
  set(IMGUI_APP_OPENGL_LOADER_GLEW ON)
elseif(IMGUI_APP_OPENGL_LOADER STREQUAL "GLAD")
  set(IMGUI_APP_OPENGL_LOADER_GLAD ON)
endif()

if(IMGUI_APP_OPENGL_LOADER_GLEW)
  find_package(GLEW REQUIRED)
  add_definitions(-DIMGUI_IMPL_OPENGL_LOADER_GLEW)
  list(APPEND IMGUI_APP_RENDERER_LIBRARIES ${GLEW_LIBRARIES})

elseif(IMGUI_APP_OPENGL_LOADER_GLAD)
  add_definitions(-DIMGUI_IMPL_OPENGL_LOADER_GLAD)
  list(APPEND IMGUI_APP_RENDERER_LIBRARIES ${GLAD_LIBRARIES})
endif()
